# Generated by Django 4.1 on 2022-08-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('watchTime', models.CharField(max_length=50)),
            ],
        ),
    ]
